  pms-client:
    build:
      context: ./pms-client
      dockerfile: infrastructure/Dockerfile
      args:
        - VITE_CLIENT_KEY=pms-client
        - VITE_AUTH_BASE_URL=https://auth.local.test:4000
        - VITE_API_URL=https://auth.local.test:4000/api/admin
        - VITE_AUTH_URL=https://auth.local.test:4000/auth
        - VITE_ACCOUNT_UI_URL=https://account.local.test:5174
        - VITE_CALLBACK_URL=https://pms-client.local.test:5677/callback
    networks:
      - sso-network
